### ISSUE TITLE
Show an "in-progress" spinner during cluster creation

### ISSUE THREAD

**Issue by viggy28** [spinup-host/spinup-dash#26]
Currently, while the cluster is being created there is no design feedback to the end-user that something is happening behind the screen. Even a simple spinner would be sufficient.

cc @araa3185

**Comment by araa3185** [comment]
yup.. we need a spinner + text saying 'Cluster is being created' for now

**Comment by viggy28** [comment]
@araa3185 can you help us with a simple design for it for now cc @skant7

**Comment by viggy28** [comment]
we have a spinner (Pacman one :)). Good to close @skant7 ?

**Comment by skant7** [comment]
Yeah we can close this
