### ISSUE TITLE
To display some avatar for username in simple auth method

### ISSUE THREAD

**Issue by viggy28** [spinup-host/spinup-dash#27]
We display Github user profile pic during Github auth whereas we don't have anything during simple auth and leave that place empty. Any default pic is better. @araa3185 had a suggestion.

**Comment by araa3185** [comment]
we can go with any hash avatar generators like:
https://robohash.org/
https://jdenticon.com/
http://identicon.net/

whichever is easy and open sourced!

**Comment by viggy28** [comment]
thanks @araa3185
